# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NtlDQGWSd2PPE2daBY-OgcZmnTglaoty
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.fft import fft, fftfreq

# Define signal parameters
f1 = 10.0  # Hz
f2 = 20.0  # Hz
fmax = max(f1, f2)
nyquist_rate = 2 * fmax

print("--- Experiment 3 - Sampling, aliasing and reconstruction ---")
print(f"Signal components: f1 = {f1} Hz, f2 = {f2} Hz")
print(f"Maximum frequency (fmax) = {fmax} Hz")
print(f"Nyquist Rate = {nyquist_rate} Hz\n")

# Define a high-resolution time vector for the "analog" continuous reference signal
# This keeps the physical sampling rate distinct from plotting resolution
t_start = 0
t_end = 0.5
fs_high = 2000.0  # High resolution for the reference signal and plotting
t_continuous = np.arange(t_start, t_end, 1/fs_high)

def x(t):
    """The two-tone signal: x(t) = sin(2*pi*f1*t) + 0.5*sin(2*pi*f2*t)"""
    return np.sin(2 * np.pi * f1 * t) + 0.5 * np.sin(2 * np.pi * f2 * t)

# Reference signal
x_continuous = x(t_continuous)

def sinc_interp(x_sampled, t_sampled, t_eval):
    """Reconstructs the signal using sinc interpolation."""
    if len(x_sampled) != len(t_sampled):
        raise ValueError('x and t must be the same length')

    Ts = t_sampled[1] - t_sampled[0]

    # Create a matrix of (t_eval - t_sampled) / Ts
    sincM = (np.tile(t_eval, (len(t_sampled), 1)) -
             np.tile(t_sampled[:, np.newaxis], (1, len(t_eval)))) / Ts

    y = np.dot(x_sampled, np.sinc(sincM))
    return y

def plot_case(fs, title):
    print(f"Simulating case: {title} (fs = {fs} Hz)")

    # 1. Sample the signal
    t_sampled = np.arange(t_start, t_end, 1/fs)
    x_sampled = x(t_sampled)

    # 2. Reconstruct using sinc interpolation
    x_reconstructed = sinc_interp(x_sampled, t_sampled, t_continuous)

    # 3. Calculate reconstruction error
    error = x_continuous - x_reconstructed

    # 4. Compute Magnitude Spectra
    N = len(t_continuous)
    # Reference spectrum
    yf_continuous = fft(x_continuous)
    xf_continuous = fftfreq(N, 1/fs_high)[:N//2]
    # Reconstructed spectrum
    yf_reconstructed = fft(x_reconstructed)

    # --- Plotting ---
    fig, axs = plt.subplots(3, 1, figsize=(10, 12))

    # Top Plot: Time domain (Reference, Sampled, Reconstructed)
    axs[0].plot(t_continuous, x_continuous, label='Reference Signal', color='gray', alpha=0.5, linewidth=3)
    axs[0].plot(t_continuous, x_reconstructed, label='Reconstructed Waveform', color='blue', linestyle='--')
    axs[0].stem(t_sampled, x_sampled, linefmt='r-', markerfmt='ro', basefmt='r-', label='Sampled Points')
    axs[0].set_title(f'Time Domain: {title} ($f_s$ = {fs} Hz)')
    axs[0].set_xlabel('Time (s)')
    axs[0].set_ylabel('Amplitude')
    axs[0].legend(loc='upper right')
    axs[0].grid(True)

    # Middle Plot: Frequency domain (Magnitude Spectra)
    axs[1].plot(xf_continuous, 2.0/N * np.abs(yf_continuous[0:N//2]), label='Reference Spectrum', color='gray', alpha=0.5, linewidth=3)
    axs[1].plot(xf_continuous, 2.0/N * np.abs(yf_reconstructed[0:N//2]), label='Reconstructed Spectrum', color='blue', linestyle='--')
    axs[1].set_title('Magnitude Spectra')
    axs[1].set_xlabel('Frequency (Hz)')
    axs[1].set_ylabel('Magnitude')
    axs[1].set_xlim(0, max(fs, 50))  # Set limit to clearly see the relevant frequencies
    axs[1].legend(loc='upper right')
    axs[1].grid(True)

    # Bottom Plot: Reconstruction error
    axs[2].plot(t_continuous, error, color='red')
    axs[2].set_title('Reconstruction Error (Reference - Reconstructed)')
    axs[2].set_xlabel('Time (s)')
    axs[2].set_ylabel('Error Amplitude')
    axs[2].grid(True)

    plt.tight_layout()

    # Save the plot
    filename = f"sampling_{title.replace(' ', '_').lower()}.png"
    plt.savefig(filename)
    print(f"-> Saved plot to {filename}\n")

# --- Run Experiments ---

# Case 1: Above Nyquist rate (e.g., 50 Hz > 40 Hz)
fs_above = 50.0
plot_case(fs_above, 'Above Nyquist Rate')

# Case 2: At Nyquist rate (40 Hz = 40 Hz)
fs_at = nyquist_rate
plot_case(fs_at, 'At Nyquist Rate')

# Case 3: Below Nyquist rate (e.g., 30 Hz < 40 Hz)
fs_below = 30.0
plot_case(fs_below, 'Below Nyquist Rate')


# --- Mandatory Validation ---
print("========================================")
print("MANDATORY VALIDATION: UNDERSAMPLED CASE")
print("========================================")
print(f"Sampling frequency: fs = {fs_below} Hz")
print(f"Nyquist frequency (folding frequency): fs/2 = {fs_below / 2} Hz\n")

# Validation for component 1 (10 Hz)
if f1 <= fs_below / 2:
    print(f"Component f1 = {f1} Hz is <= {fs_below / 2} Hz.")
    print("-> Result: No aliasing for this component.")
else:
    f1_alias = abs(f1 - fs_below * round(f1 / fs_below))
    print(f"Component f1 = {f1} Hz is > {fs_below / 2} Hz.")
    print(f"-> Result: Aliases to |{f1} - {fs_below}*k| = {f1_alias} Hz")

print("")

# Validation for component 2 (20 Hz)
if f2 <= fs_below / 2:
    print(f"Component f2 = {f2} Hz is <= {fs_below / 2} Hz.")
    print("-> Result: No aliasing for this component.")
else:
    k = round(f2 / fs_below)
    f2_alias = abs(f2 - fs_below * k)
    print(f"Component f2 = {f2} Hz is > {fs_below / 2} Hz.")
    print(f"-> Result: Aliases to |{f2} - {fs_below} * {k}| = {f2_alias} Hz")

print(f"\nConclusion for undersampled case (fs = {fs_below} Hz):")
print(f"The 20 Hz component aliases down to {f2_alias} Hz.")
print(f"Therefore, the reconstructed signal will appear as a sum of 10 Hz components.")